var searchData=
[
  ['de_20obsoletos_0',['Lista de obsoletos',['../deprecated.html',1,'']]],
  ['deallocate_1',['deallocate',['../struct_g_l_f_wallocator.html#ab74cf9a969e73e6eb65a6112a591a988',1,'GLFWallocator']]],
  ['defineinfo_2',['DefineInfo',['../struct_define_info.html',1,'']]],
  ['denominacion_3',['denominacion',['../structcarta.html#a8947f87e0cd7c5fa51eacc085f397fbb',1,'carta']]],
  ['dependencies_4',['What are raylib&apos;s external dependencies?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md29',1,'']]],
  ['developers_5',['Who are the raylib developers?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md34',1,'']]],
  ['development_20tools_20are_20required_20for_20raylib_6',['What development tools are required for raylib?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md28',1,'']]],
  ['dibujarboton_7',['DibujarBoton',['../_interfaz_8hpp.html#ac1ecc21fb55c6d0a32726705c7be5df1',1,'Interfaz.cpp']]],
  ['dibujarnotificacion_8',['DibujarNotificacion',['../_interfaz_8hpp.html#a2a211a09864f3d56e6f7eb6107669eee',1,'Interfaz.cpp']]],
  ['dicondition_9',['DICONDITION',['../struct_d_i_c_o_n_d_i_t_i_o_n.html',1,'']]],
  ['diconstantforce_10',['DICONSTANTFORCE',['../struct_d_i_c_o_n_s_t_a_n_t_f_o_r_c_e.html',1,'']]],
  ['dicustomforce_11',['DICUSTOMFORCE',['../struct_d_i_c_u_s_t_o_m_f_o_r_c_e.html',1,'']]],
  ['didevcaps_12',['DIDEVCAPS',['../struct_d_i_d_e_v_c_a_p_s.html',1,'']]],
  ['didevcaps_5fdx3_13',['DIDEVCAPS_DX3',['../struct_d_i_d_e_v_c_a_p_s___d_x3.html',1,'']]],
  ['dideviceinstance_5fdx3a_14',['DIDEVICEINSTANCE_DX3A',['../struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e___d_x3_a.html',1,'']]],
  ['dideviceinstance_5fdx3w_15',['DIDEVICEINSTANCE_DX3W',['../struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e___d_x3_w.html',1,'']]],
  ['dideviceinstancea_16',['DIDEVICEINSTANCEA',['../struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e_a.html',1,'']]],
  ['dideviceinstancew_17',['DIDEVICEINSTANCEW',['../struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e_w.html',1,'']]],
  ['dideviceobjectdata_18',['DIDEVICEOBJECTDATA',['../struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_d_a_t_a.html',1,'']]],
  ['dideviceobjectdata_5fdx3_19',['DIDEVICEOBJECTDATA_DX3',['../struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_d_a_t_a___d_x3.html',1,'']]],
  ['dideviceobjectinstance_5fdx3a_20',['DIDEVICEOBJECTINSTANCE_DX3A',['../struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e___d_x3_a.html',1,'']]],
  ['dideviceobjectinstance_5fdx3w_21',['DIDEVICEOBJECTINSTANCE_DX3W',['../struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e___d_x3_w.html',1,'']]],
  ['dideviceobjectinstancea_22',['DIDEVICEOBJECTINSTANCEA',['../struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e_a.html',1,'']]],
  ['dideviceobjectinstancew_23',['DIDEVICEOBJECTINSTANCEW',['../struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e_w.html',1,'']]],
  ['dieffect_24',['DIEFFECT',['../struct_d_i_e_f_f_e_c_t.html',1,'']]],
  ['dieffect_5fdx5_25',['DIEFFECT_DX5',['../struct_d_i_e_f_f_e_c_t___d_x5.html',1,'']]],
  ['dieffectinfoa_26',['DIEFFECTINFOA',['../struct_d_i_e_f_f_e_c_t_i_n_f_o_a.html',1,'']]],
  ['dieffectinfow_27',['DIEFFECTINFOW',['../struct_d_i_e_f_f_e_c_t_i_n_f_o_w.html',1,'']]],
  ['dieffescape_28',['DIEFFESCAPE',['../struct_d_i_e_f_f_e_s_c_a_p_e.html',1,'']]],
  ['dienvelope_29',['DIENVELOPE',['../struct_d_i_e_n_v_e_l_o_p_e.html',1,'']]],
  ['difileeffect_30',['DIFILEEFFECT',['../struct_d_i_f_i_l_e_e_f_f_e_c_t.html',1,'']]],
  ['dijoystate_31',['DIJOYSTATE',['../struct_d_i_j_o_y_s_t_a_t_e.html',1,'']]],
  ['dijoystate2_32',['DIJOYSTATE2',['../struct_d_i_j_o_y_s_t_a_t_e2.html',1,'']]],
  ['dimousestate_33',['DIMOUSESTATE',['../struct_d_i_m_o_u_s_e_s_t_a_t_e.html',1,'']]],
  ['dimousestate2_34',['DIMOUSESTATE2',['../struct_d_i_m_o_u_s_e_s_t_a_t_e2.html',1,'']]],
  ['diperiodic_35',['DIPERIODIC',['../struct_d_i_p_e_r_i_o_d_i_c.html',1,'']]],
  ['dipropcal_36',['DIPROPCAL',['../struct_d_i_p_r_o_p_c_a_l.html',1,'']]],
  ['dipropcalpov_37',['DIPROPCALPOV',['../struct_d_i_p_r_o_p_c_a_l_p_o_v.html',1,'']]],
  ['dipropcpoints_38',['DIPROPCPOINTS',['../struct_d_i_p_r_o_p_c_p_o_i_n_t_s.html',1,'']]],
  ['dipropdword_39',['DIPROPDWORD',['../struct_d_i_p_r_o_p_d_w_o_r_d.html',1,'']]],
  ['dipropguidandpath_40',['DIPROPGUIDANDPATH',['../struct_d_i_p_r_o_p_g_u_i_d_a_n_d_p_a_t_h.html',1,'']]],
  ['dipropheader_41',['DIPROPHEADER',['../struct_d_i_p_r_o_p_h_e_a_d_e_r.html',1,'']]],
  ['diproppointer_42',['DIPROPPOINTER',['../struct_d_i_p_r_o_p_p_o_i_n_t_e_r.html',1,'']]],
  ['diproprange_43',['DIPROPRANGE',['../struct_d_i_p_r_o_p_r_a_n_g_e.html',1,'']]],
  ['dipropstring_44',['DIPROPSTRING',['../struct_d_i_p_r_o_p_s_t_r_i_n_g.html',1,'']]],
  ['dir_45',['DIR',['../struct_d_i_r.html',1,'']]],
  ['dirampforce_46',['DIRAMPFORCE',['../struct_d_i_r_a_m_p_f_o_r_c_e.html',1,'']]],
  ['directories_20and_20the_20resources_20folder_47',['Working directories and the resources folder',['../C:/Users/GamerHouse/Documents/0_UNISON/Programacion I/BlackJack/BlackJack/README.md#autotoc_md84',1,'']]],
  ['directories_20naming_20conventions_48',['Files and Directories Naming Conventions',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_blde42997374744c47372c15a7ee8a6431.html#autotoc_md12',1,'']]],
  ['directories_20organization_20conventions_49',['Games/Examples Directories Organization Conventions',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_blde42997374744c47372c15a7ee8a6431.html#autotoc_md13',1,'']]],
  ['dirent_50',['dirent',['../structdirent.html',1,'']]],
  ['do_20with_20raylib_51',['What can I do with raylib?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md16',1,'']]],
  ['docs_52',['learning and docs',['../C:/Users/GamerHouse/Documents/0_UNISON/Programacion I/BlackJack/BlackJack/build/external/raylib-master/README.md#autotoc_md65',1,'']]],
  ['documentation_20or_20tutorials_53',['How can I learn to use raylib? Is there some official documentation or tutorials?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md19',1,'']]],
  ['does_20it_20cost_54',['How much does it cost?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md20',1,'']]],
  ['does_20raylib_20compare_20to_20unity_20unreal_20godot_55',['How does raylib compare to Unity/Unreal/Godot?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md27',1,'']]],
  ['does_20raylib_20provide_20that_20other_20engines_20or_20libraries_20don_20t_56',['What does raylib provide that other engines or libraries don&apos;t?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md26',1,'']]],
  ['does_20raylib_20support_20the_20vulkan_20api_57',['Does raylib support the Vulkan API?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md32',1,'']]],
  ['don_20t_58',['What does raylib provide that other engines or libraries don&apos;t?',['../md__c_1_2_users_2_gamer_house_2_documents_20___u_n_i_s_o_n_2_programacion_01_i_2_black_jack_2_bl5ed7e5edc19b68ff8dd4eb93cdd545f8.html#autotoc_md26',1,'']]],
  ['drflac_59',['drflac',['../structdrflac.html',1,'']]],
  ['drflac_5f_5fmemory_5fstream_60',['drflac__memory_stream',['../structdrflac____memory__stream.html',1,'']]],
  ['drflac_5fallocation_5fcallbacks_61',['drflac_allocation_callbacks',['../structdrflac__allocation__callbacks.html',1,'']]],
  ['drflac_5fbs_62',['drflac_bs',['../structdrflac__bs.html',1,'']]],
  ['drflac_5fcuesheet_5ftrack_63',['drflac_cuesheet_track',['../structdrflac__cuesheet__track.html',1,'']]],
  ['drflac_5fcuesheet_5ftrack_5findex_64',['drflac_cuesheet_track_index',['../structdrflac__cuesheet__track__index.html',1,'']]],
  ['drflac_5fcuesheet_5ftrack_5fiterator_65',['drflac_cuesheet_track_iterator',['../structdrflac__cuesheet__track__iterator.html',1,'']]],
  ['drflac_5fframe_66',['drflac_frame',['../structdrflac__frame.html',1,'']]],
  ['drflac_5fframe_5fheader_67',['drflac_frame_header',['../structdrflac__frame__header.html',1,'']]],
  ['drflac_5fmetadata_68',['drflac_metadata',['../structdrflac__metadata.html',1,'']]],
  ['drflac_5fseekpoint_69',['drflac_seekpoint',['../structdrflac__seekpoint.html',1,'']]],
  ['drflac_5fstreaminfo_70',['drflac_streaminfo',['../structdrflac__streaminfo.html',1,'']]],
  ['drflac_5fsubframe_71',['drflac_subframe',['../structdrflac__subframe.html',1,'']]],
  ['drflac_5fvorbis_5fcomment_5fiterator_72',['drflac_vorbis_comment_iterator',['../structdrflac__vorbis__comment__iterator.html',1,'']]],
  ['drmp3_73',['drmp3',['../structdrmp3.html',1,'']]],
  ['drmp3_5fallocation_5fcallbacks_74',['drmp3_allocation_callbacks',['../structdrmp3__allocation__callbacks.html',1,'']]],
  ['drmp3_5fconfig_75',['drmp3_config',['../structdrmp3__config.html',1,'']]],
  ['drmp3_5fseek_5fpoint_76',['drmp3_seek_point',['../structdrmp3__seek__point.html',1,'']]],
  ['drmp3dec_77',['drmp3dec',['../structdrmp3dec.html',1,'']]],
  ['drmp3dec_5fframe_5finfo_78',['drmp3dec_frame_info',['../structdrmp3dec__frame__info.html',1,'']]],
  ['droppedfiles_79',['droppedFiles',['../struct_r_g_f_w__event.html#af29ce01704933b5865407225802c841f',1,'RGFW_event']]],
  ['droppedfilescount_80',['droppedFilesCount',['../struct_r_g_f_w__event.html#a5046663caad1f8af75d2cb4bc9a311fc',1,'RGFW_event']]],
  ['drwav_81',['drwav',['../structdrwav.html',1,'']]],
  ['drwav_5f_5fmemory_5fstream_82',['drwav__memory_stream',['../structdrwav____memory__stream.html',1,'']]],
  ['drwav_5f_5fmemory_5fstream_5fwrite_83',['drwav__memory_stream_write',['../structdrwav____memory__stream__write.html',1,'']]],
  ['drwav_5facid_84',['drwav_acid',['../structdrwav__acid.html',1,'']]],
  ['drwav_5fallocation_5fcallbacks_85',['drwav_allocation_callbacks',['../structdrwav__allocation__callbacks.html',1,'']]],
  ['drwav_5fbext_86',['drwav_bext',['../structdrwav__bext.html',1,'']]],
  ['drwav_5fchunk_5fheader_87',['drwav_chunk_header',['../structdrwav__chunk__header.html',1,'']]],
  ['drwav_5fcue_88',['drwav_cue',['../structdrwav__cue.html',1,'']]],
  ['drwav_5fcue_5fpoint_89',['drwav_cue_point',['../structdrwav__cue__point.html',1,'']]],
  ['drwav_5fdata_5fformat_90',['drwav_data_format',['../structdrwav__data__format.html',1,'']]],
  ['drwav_5ffmt_91',['drwav_fmt',['../structdrwav__fmt.html',1,'']]],
  ['drwav_5finst_92',['drwav_inst',['../structdrwav__inst.html',1,'']]],
  ['drwav_5flist_5finfo_5ftext_93',['drwav_list_info_text',['../structdrwav__list__info__text.html',1,'']]],
  ['drwav_5flist_5flabel_5for_5fnote_94',['drwav_list_label_or_note',['../structdrwav__list__label__or__note.html',1,'']]],
  ['drwav_5flist_5flabelled_5fcue_5fregion_95',['drwav_list_labelled_cue_region',['../structdrwav__list__labelled__cue__region.html',1,'']]],
  ['drwav_5fmetadata_96',['drwav_metadata',['../structdrwav__metadata.html',1,'']]],
  ['drwav_5fsmpl_97',['drwav_smpl',['../structdrwav__smpl.html',1,'']]],
  ['drwav_5fsmpl_5floop_98',['drwav_smpl_loop',['../structdrwav__smpl__loop.html',1,'']]],
  ['drwav_5funknown_5fmetadata_99',['drwav_unknown_metadata',['../structdrwav__unknown__metadata.html',1,'']]],
  ['dwm_5fblurbehind_100',['DWM_BLURBEHIND',['../struct_d_w_m___b_l_u_r_b_e_h_i_n_d.html',1,'']]]
];
